return workflow result with container name
Matrinos/iot-device-simulator-docker-runner pull request #12
Opened 2021-07-01 09:40 UTC by ajaxjiang96

2021-07-01 12:09 UTC, qs-wang requested changes

2021-07-01 12:09 UTC, qs-wang commented on workflow.go
> +		return nil, err
return SimulatorStartResult{}, err

2021-07-01 12:09 UTC, qs-wang commented on workflow.go
> +		return nil, err
return SimulatorStartResult{}, err

2021-07-01 12:09 UTC, qs-wang commented on workflow.go
> +		return nil, err
return SimulatorStartResult{}, err

2021-07-02 05:17 UTC, ajaxjiang96 commented on workflow.go
> +		return nil, err
Done

2021-07-02 05:17 UTC, ajaxjiang96 commented on workflow.go
> +		return nil, err
Done

2021-07-02 08:18 UTC, qs-wang approved these changes

2021-07-02 08:22 UTC, merged